### ISSUE TITLE
can't install coMethDMR 

### ISSUE THREAD

**Issue by chaoqianglai** [lissettegomez/coMethDMR#4]
Hi,
I tried to install coMethDMR in my work station (Window) with R 4.0.3 following your manual.
But it ran into this error (stopped at this message):

* installing *source* package 'SummarizedExperiment' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: package or namespace load failed for 'GenomeInfoDb' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called 'GenomeInfoDbData'
Error: package 'GenomeInfoDb' could not be loaded
Execution halted
ERROR: lazy loading failed for package 'SummarizedExperiment'
* removing 'C:/Users/clai04.HNRC/Documents/R/win-library/4.0/SummarizedExperiment'
Error: Failed to install 'coMethDMR' from GitHub:
  (converted from warning) installation of package ‘SummarizedExperiment’ had non-zero exit status

Please advise any solution to issue.

Thank you,

Chao-Qiang Lai

**Comment by chaoqianglai** [comment]
Never mind - problem resolved. 
Window can't unzip the downloaded files automatically, which prevents it from installing the downloaded files.

**Comment by gabrielodom** [comment]
Hello Prof. Lai, 
We are very pleased that you were able to solve your own issue. 
Please do not hesitate to ask any questions you may have about the software. We are still making effort to submit this package to Bioconductor within the next few months, so that should make installing the package easier in the future.
Warm regards,
Gabriel
